import type { Metadata } from "next";
import localFont from "next/font/local";
import { Princess_Sofia } from "next/font/google";
import "./globals.css";
import WalletAdapterProvider from "./WalletAdapterProvider";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const PrincessSofia = Princess_Sofia({
	subsets: ["latin"],
	weight: ["400"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<WalletAdapterProvider>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					{children}
					<Toaster />
				</body>
			</WalletAdapterProvider>
		</html>
	);
}
